-- Insert Category
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('OUTERWEAR', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('TOPS', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('BOTTOMS', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('DRESSES & SKIRTS', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('INNERWEAR & UNDERWEAR', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & HOMEWEAR', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ACCESSORIES', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('MATERNITY CLOTHES', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('OUTERWEAR', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('TOPS', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('BOTTOMS', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('INNERWEAR & UNDERWEAR', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & HOMEWEAR', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ACCESSORIES', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('OUTERWEAR', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('TOPS', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('BOTTOMS', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('DRESSES & SKIRTS', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('INNERWEAR & UNDERWEAR', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & HOMEWEAR', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ACCESSORIES', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('NEWBORN (0 - 3 MONTHS)', 'BABY', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('NEWBORN (3 - 24 MONTHS)', 'BABY', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('TODDLER (6 MONTHS - 5 YEARS)', 'BABY', '1');
-- Insert Subcategory
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ULTRA LIGHT DOWN & PUFFTECH', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BLOUSONS & PARKAS', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JACKETS & BLAZERS', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('COATS', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('FLEECE', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATSHIRTS & HOODIES', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATERS', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('CARDIGANS', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('T-SHIRTS', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UT GRAPHIC TEES', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SHIRTS & BLOUSES', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PEACE FOR ALL', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JEANS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('CASUAL PANTS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('WIDE LEG PANTS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ANKLE & CROPPED PANTS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TROUSERS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEAT PANTS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LEGGINGS PANTS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('DRESSES', '4', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SKIRTS', '4', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', '5', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('HEATTECH INNERWEAR & THERMAL UNDERWEAR', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRISM INNERWEAR', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BRAS', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BRA TOPS', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UNDERWEAR', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LEGGINGS & TIGHTS', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SOCKS', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & PAJAMAS', '7', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('EASY & RELAXED PANTS', '7', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ROOM SHOES', '7', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BAGS', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('HATS & CAPS', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SCARVES & STOLES', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('GLOVES', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BELTS', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SHOES & BOOTS', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UMBRELLAS', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SUNGLASSES', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('MATERNITY', '9', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ULTRA LIGHT DOWN & PUFFTECH', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BLOUSONS & PARKAS', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRSENSE ÁO KHOÁC SIÊU NHẸ', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JACKETS & BLAZERS', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('COATS', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('FLEECE', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATSHIRTS & HOODIES', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATERS', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('T-SHIRTS', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('POLO SHIRTS', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UT GRAPHIC TEES', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('CASUAL SHIRTS', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('DRESS SHIRTS (FORMAL SHIRTS)', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PEACE FOR ALL', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JEANS & COLORED JEANS', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('EASY PANTS', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ANKLE PANTS', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRSENSE PANTS', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TROUSERS', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('WIDE LEG PANTS', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEAT PANTS', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SHORTS', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('CHINOS', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', '13', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('HEATTECH INNERWEAR & THERMAL UNDERWEAR', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRISM INNERWEAR', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BOXERS & BRIEFS', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LEGGINGS & TIGHTS', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SOCKS', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & PAJAMAS', '15', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('EASY & RELAXED PANTS', '15', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ROOM SHOES', '15', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BAGS', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('HATS & CAPS', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SCARVES & STOLES', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('GLOVES', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BELTS', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SUNGLASSES', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UMBRELLAS', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BLOUSONS & PARKAS', '17', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JACKETS & COATS', '17', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('FLEECE', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATSHIRTS & HOODIES', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATERS & ÁO CARDIGANS', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('T-SHIRTS', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UT GRAPHIC TEES', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SHIRTS & BLOUSES', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JEANS', '19', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PANTS', '19', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SHORTS', '19', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('DRESSES', '20', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SKIRTS', '20', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', '21', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('HEATTECH INNERWEAR & THERMAL UNDERWEAR', '22', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRISM INNERWEAR', '22', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BRAS & BRA TOPS', '22', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UNDERWEAR', '22', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SOCKS', '22', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & PAJAMAS', '23', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('GLOVES', '24', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('HATS', '24', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BIRTH PREPARATION ITEMS', '25', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ACCESSORIES', '25', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('OUTERWEAR', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ONE-PIECES', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BODYSUIT', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TOPS', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PANTS & LEGGINGS', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SOCKS', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ACCESSORIES', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('OUTERWEAR', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TOPS', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UT GRAPHIC TEES', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PANTS & LEGGINGS', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & PAJAMAS', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('HEATTECH INNERWEAR & THERMAL UNDERWEAR', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SOCKS', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ACCESSORIES', '27', '1');