-- Insert Category
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('OUTERWEAR', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('TOPS', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('BOTTOMS', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('DRESSES & SKIRTS', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('INNERWEAR & UNDERWEAR', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & HOMEWEAR', 'WOMEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('OUTERWEAR', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('TOPS', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('BOTTOMS', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('INNERWEAR & UNDERWEAR', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & HOMEWEAR', 'MEN', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('OUTERWEAR', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('TOPS', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('BOTTOMS', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('DRESSES & SKIRTS', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('INNERWEAR & UNDERWEAR', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & HOMEWEAR', 'KIDS', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('NEWBORN (0 - 3 MONTHS)', 'BABY', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('NEWBORN (3 - 24 MONTHS)', 'BABY', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('TODDLER (6 MONTHS - 5 YEARS)', 'BABY', '1');
-- Insert Subcategory
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ULTRA LIGHT DOWN & PUFFTECH', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BLOUSONS & PARKAS', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JACKETS & BLAZERS', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('COATS', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('FLEECE', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATSHIRTS & HOODIES', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATERS', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('CARDIGANS', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('T-SHIRTS', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UT GRAPHIC TEES', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SHIRTS & BLOUSES', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PEACE FOR ALL', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JEANS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('CASUAL PANTS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('WIDE LEG PANTS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ANKLE & CROPPED PANTS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TROUSERS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEAT PANTS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LEGGINGS PANTS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('DRESSES', '4', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SKIRTS', '4', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BRAS', '5', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BRA TOPS', '5', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UNDERWEAR', '5', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LEGGINGS & TIGHTS', '5', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & PAJAMAS', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('EASY & RELAXED PANTS', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ULTRA LIGHT DOWN & PUFFTECH', '7', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BLOUSONS & PARKAS', '7', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRSENSE JACKETS', '7', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JACKETS & BLAZERS', '7', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('COATS', '7', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('FLEECE', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATSHIRTS & HOODIES', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATERS', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('T-SHIRTS', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('POLO SHIRTS', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UT GRAPHIC TEES', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('CASUAL SHIRTS', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('DRESS SHIRTS (FORMAL SHIRTS)', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PEACE FOR ALL', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JEANS & COLORED JEANS', '9', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('EASY PANTS', '9', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ANKLE PANTS', '9', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRSENSE PANTS', '9', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('WIDE LEG PANTS', '9', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEAT PANTS', '9', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SHORTS', '9', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BOXERS & BRIEFS', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LEGGINGS & TIGHTS', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & PAJAMAS', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('EASY & RELAXED PANTS', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BLOUSONS & PARKAS', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JACKETS & COATS', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATSHIRTS & HOODIES', '13', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SWEATERS & CARDIGANS', '13', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('T-SHIRTS', '13', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UT GRAPHIC TEES', '13', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SHIRTS & BLOUSES', '13', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JEANS', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PANTS', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SHORTS', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('DRESSES', '15', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SKIRTS', '15', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BRAS & BRA TOPS', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UNDERWEAR', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & PAJAMAS', '17', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BIRTH PREPARATION ITEMS', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('OUTERWEAR', '19', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TOPS', '19', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PANTS & LEGGINGS', '19', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TOPS', '20', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('UT GRAPHIC TEES', '20', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PANTS & LEGGINGS', '20', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('LOUNGEWEAR & PAJAMAS', '20', '1');
