-- Insert Product
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Light Down Vest', '980000', '1', '1');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Light Down Jacket', '1668000', '1', '1');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Light Down Parka', '1668000', '1', '1');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Pocketable UV Protection Parka', '980000', '1', '2');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Seamless Down Parka', '2944000', '1', '2');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Smooth Jersey Lined Parka', '784000', '1', '2');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Light Down Jacket', '1962000', '1', '3');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Powder Soft Down Jacket (Nanodesign)', '1962000', '1', '3');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Fluffy Yarn Fleece Full-Zip Jacket', '686000', '1', '3');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Pile Lined Fleece Stand Collar Coat', '1668000', '1', '4');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Double Face Wrap Coat', '1962000', '1', '4');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Double Face Long Coat', '2453000', '1', '4');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('JW Anderson Pile Lined Fleece Printed Full-Zip Hoodie', '980000', '2', '5');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Soft Knitted Fleece Crew Neck Long Sleeve T-Shirt', '391000', '2', '5');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('HEATTECH Fleece Turtleneck Long Sleeve T-Shirt', '391000', '2', '5');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Half-Zip Sweatshirt', '686000', '2', '6');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Sweat Long Sleeve Full-Zip Hoodie', '784000', '2', '6');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Mesh UV Protection Full-Zip Hoodie', '686000', '2', '6');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Extra Fine Merino Long Sleeve Crew Neck Sweater', '784000', '2', '7');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Light Souffle Yarn High Neck Long Sleeve Sweater', '784000', '2', '7');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('JW Anderson Souffle Yarn Color Mix Crew Neck Long Sleeve Sweater', '784000', '2', '7');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('UV Protection Crew Neck Cardigan', '489000', '2', '8');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Merino Blend Long Sleeve Crew Neck Cardigan', '980000', '2', '8');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Premium Lambswool Long Sleeve Cardigan', '784000', '2', '8');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('SUPIMA COTTON Crew Neck Short Sleeve T-Shirt', '293000', '2', '9');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Crew Neck Short Sleeve T-Shirt', '293000', '2', '9');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Mini Short Sleeve T-Shirt', '293000', '2', '9');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Sanrio Characters Short Sleeve UT', '391000', '2', '10');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('PEANUTS Short Sleeve UT', '391000', '2', '10');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Winnie The Pooh Collaboration Long Sleeve Set', '784000', '2', '10');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Premium Linen Long Sleeve Shirt', '980000', '2', '11');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Rayon Long Sleeve Blouse', '588000', '2', '11');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Rayon Short Sleeve Blouse', '489000', '2', '11');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('PEACE FOR ALL (Magnum Photos)(Short Sleeve T-Shirt)', '391000', '2', '12');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('PEACE FOR ALL (Daido Moriyama)(Short Sleeve T-Shirt)', '391000', '2', '12');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('PEACE FOR ALL (Akamai Technologies)(Short Sleeve T-Shirt)', '391000', '2', '12');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('JW Anderson Slim Straight Jeans', '980000', '3', '13');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Stretch Slim Straight Jeans', '980000', '3', '13');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch Maternity Jeans', '980000', '3', '13');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch Waffle Straight Pants', '489000', '3', '14');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch AIRism Jogger Pants', '489000', '3', '14');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Denim Jersey Tapered Pants', '588000', '3', '14');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Brushed Jersey Wide Pants', '784000', '3', '15');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Corduroy Pleated Wide Pants', '784000', '3', '15');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Tweed Pleated Wide Pants', '1668000', '3', '15');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Smart Ankle Pants', '784000', '3', '16');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch High Rise Cropped Leggings Pants', '588000', '3', '16');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Smart Ankle Pants (Checked)', '784000', '3', '16');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Smart Short', '588000', '3', '17');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Smart Tucked Shorts', '588000', '3', '17');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('HEATTECH Pile Lined Sweat Pants', '784000', '3', '18');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Sweat Pants', '686000', '3', '18');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch Denim Leggings Pants', '588000', '3', '19');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch Leggings Pants', '588000', '3', '19');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('JW Anderson Ribbed Long Sleeve Knit Dress', '980000', '4', '20');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Souffle Yarn Long Sleeve Dress', '980000', '4', '20');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Mercerized Cotton Short Sleeve A Line Dress', '588000', '4', '20');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Easy Cargo Skirt', '784000', '4', '21');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Chiffon Pleated Skirt', '1275000', '4', '21');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Premium Lambswool Mini Skirt', '784000', '4', '21');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Wireless Bra (3D Hold)', '489000', '5', '22');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Wireless Bra (Ultra Relax)', '489000', '5', '22');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Wireless Bra (Relax/Plunging Lace)', '489000', '5', '22');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('American Sleeve Cropped Bra Sleeveless Top', '489000', '5', '23');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Cotton Cropped Bra Tube Top', '489000', '5', '23');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Seamless Half Bra Camisole', '489000', '5', '23');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Ultra Seamless Shorts Regular Shorts', '146000', '5', '24');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Ultra Seamless Shorts High Rise Briefs', '146000', '5', '24');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Ultra Seamless Shorts (Hiphugger)', '146000', '5', '24');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('HEATTECH Knitted Tights (Ribbed)', '391000', '5', '25');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('HEATTECH Ultra Warm Leggings', '588000', '5', '25');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('HEATTECH Cotton Leggings (Extra Warm)', '489000', '5', '25');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Cotton Pajamas (Long Sleeve)', '784000', '6', '26');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Cotton Pajamas (Short Sleeve)', '588000', '6', '26');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch Set (Long Sleeve)', '784000', '6', '26');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Flannel Pants', '489000', '6', '27');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Washable Knit Ribbed Pants', '489000', '6', '27');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Cotton Relaxed Ankle Pants', '489000', '6', '27');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Light Down Vest', '980000', '7', '28');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Light Down Jacket (3D Cut)', '1668000', '7', '28');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Light Down Parka (3D Cut)', '1668000', '7', '28');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Blocktech Parka (3D Cut)', '1471000', '7', '29');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Pocketable UV Protection Parka (3D Cut)', '980000', '7', '29');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Reversible Parka', '980000', '7', '29');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AirSense Jacket (Wool Like)', '1471000', '7', '30');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AirSense Jacket (Cotton Like)', '1471000', '7', '30');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AirSense Jacket (Ultra Light Jacket) (Wool Like)', '1471000', '7', '30');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Comfort 2B Jacket', '1471000', '7', '31');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Powder Soft Down Jacket (Nanodesign)', '2944000', '7', '31');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Fluffy Yarn Fleece Full-Zip Jacket', '686000', '7', '31');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('PUFFTECH Hooded Coat (HEATTECH)', '2944000', '7', '32');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('JW Anderson Trench Coat', '1962000', '7', '32');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Padded Single Breasted Coat', '2944000', '7', '32');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Stretch Fleece Mock Neck Long Sleeve T-Shirt', '489000', '8', '33');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Stretch Fleece Print Mock Neck Long Sleeve T-Shirt', '489000', '8', '33');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Stretch Fleece Half Zip Long Sleeve', '489000', '8', '33');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Sweatshirt', '686000', '8', '34');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Sweat Pullover Hoodie', '784000', '8', '34');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Sweat Long Sleeve Full-Zip Hoodie', '784000', '8', '34');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Extra Fine Merino Crew Neck Long Sleeve Sweater', '784000', '8', '35');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Souffle Yarn Cable Long Sleeve Crew Neck Sweater', '980000', '8', '35');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('3D Knit Souffle Yarn Mock Neck Sweater', '980000', '8', '35');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Crew Neck Short Sleeve T-Shirt', '293000', '8', '36');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Supima Cotton Crew Neck Short Sleeve T-Shirt', '391000', '8', '36');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Cotton Crew Neck Oversized T-Shirt', '391000', '8', '36');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Dry Pique Short Sleeve Polo Shirt', '489000', '8', '37');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Dry-EX Short Sleeve Polo Shirt', '489000', '8', '37');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Short Sleeve Polo Shirt (Regular Collar)', '489000', '8', '37');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Hunter X Hunter Anime Short Sleeve UT', '391000', '8', '38');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KAWS Short Sleeve UT', '391000', '8', '38');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('JUJUTSU KAISEN Short Sleeve UT', '391000', '8', '38');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Stand Collar Short Sleeve Shirt', '588000', '8', '39');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('OXford Slim Fit Long Sleeve Shirt', '588000', '8', '39');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Modal Cotton Open Collar Short Sleeve Shirt', '588000', '8', '39');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Super Non Iron Slim Fit Long Sleeve Shirt', '784000', '8', '40');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Easy Care Stretch Slim Fit Long Sleeve Shirt', '784000', '8', '40');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Non Iron Jersey Long Sleeve Shirt', '784000', '8', '40');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('PEACE FOR ALL (Keith Haring) (Short Sleeve T-Shirt)', '391000', '8', '41');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('PEACE FOR ALL (Haruka Ayase) (Short Sleeve T-Shirt)', '391000', '8', '41');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('PEACE FOR ALL (Julian Opie) (Short Sleeve T-Shirt)', '391000', '8', '41');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch Jeans', '980000', '9', '42');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch Color Jeans', '784000', '9', '42');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Slim Fit Jeans', '980000', '9', '42');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch Dry-EX Jogger Pants', '686000', '9', '43');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch Dry-EX Tapered Pants', '686000', '9', '43');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Wide Fit Parachute Cargo Pants', '980000', '9', '43');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Smart Ankle Pants (Wool Like)', '784000', '9', '44');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Smart Ankle Pants (Cotton)', '784000', '9', '44');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Smart Ankle Pants (Corduroy)', '784000', '9', '44');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AirSense Pants (Ultra Light Pants)', '980000', '9', '45');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AirSense Pants 2WAY Stretch (Ultra Light Pants)', '980000', '9', '45');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AirSense Shorts (Ultra Light Shorts)', '784000', '9', '45');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Wide Fit Parachute Cargo Pants', '980000', '9', '46');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Wide Fit Chino Pants', '980000', '9', '46');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Pleated Wide Pants', '784000', '9', '46');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Sweat Pants', '686000', '9', '47');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Dry Stretch Sweat Pants', '686000', '9', '47');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('HEATTECH Pile Lined Sweat Pants', '784000', '9', '47');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Stretch Slim Fit Shorts', '588000', '9', '48');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Chino Shorts', '588000', '9', '48');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Geared Shorts', '588000', '9', '48');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Printed Boxer Briefs', '244000', '10', '49');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Striped Boxer Briefs', '244000', '10', '49');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism Boxer Briefs', '244000', '10', '49');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('HEATTECH Ultra Warm Long Johns', '588000', '10', '50');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('HEATTECH Tights', '293000', '10', '50');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('HEATTECH Long Johns', '293000', '10', '50');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Washed Jersey Easy Shorts', '391000', '11', '51');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ultra Stretch Sweat Set (Long Sleeve)', '784000', '11', '51');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Flannel Easy Ankle Pants', '686000', '11', '51');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Cotton Relaxed Ankle Pants', '588000', '11', '52');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS PUFFTECH Washable Parka (Warm Padded)', '980000', '12', '53');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS PUFFTECH Washable Vest (Warm Padded)', '588000', '12', '53');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS PUFFTECH Washable Cardigan (Warm Padded)', '784000', '12', '53');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Printed Fleece Full-Zip Jacket', '489000', '12', '54');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Sweat Stadium Jacket', '784000', '12', '54');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Fluffy Yarn Fleece Full-Zip Jacket', '489000', '12', '54');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('GIRLS Sanrio characters Sweat Cropped Long Sleeve Hoodie', '489000', '13', '55');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Ultra Stretch Long Sleeve Sweatshirt', '391000', '13', '55');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Ultra Stretch Dry Sweat Long Sleeve Full-Zip Hoodie', '489000', '13', '55');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Souffle Yarn Long Sleeve Sweater', '489000', '13', '56');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Middle Gauge V Neck Cardigan', '489000', '13', '56');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('GIRLS Souffle Yarn V Neck Cardigan', '489000', '13', '56');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS HEATTECH Cotton Waffle Crew Neck T-Shirt', '293000', '13', '57');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Ribbed Fleece High Neck Long Sleeve T-Shirt', '244000', '13', '57');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Cotton Color Crew Neck Short Sleeve T-Shirt', '126000', '13', '57');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Mickey Shines Short Sleeve UT', '244000', '13', '58');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Studio Ghibli Short Sleeve UT', '244000', '13', '58');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Mickey Stands Short Sleeve UT', '244000', '13', '58');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Flannel Checked Long Sleeve Shirt', '489000', '13', '59');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Dry Pique Striped Short Sleeve Polo Shirt', '391000', '13', '59');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('GIRLS Baggy Jeans', '588000', '14', '60');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Ultra Stretch Soft Jeans', '489000', '14', '60');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Ultra Stretch Graphic Sweat Pants', '489000', '14', '61');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Ultra Stretch Dry Sweat Pants', '391000', '14', '61');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Ultra Stretch Dry-EX Jogger Pants', '391000', '14', '61');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Stretch Easy Shorts', '293000', '14', '62');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('GIRLS Easy Color Shorts', '293000', '14', '62');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS Stretch Twill Easy Shorts', '293000', '14', '62');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('GIRLS Rayon Flower Printed Short Sleeve Dress', '489000', '15', '63');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('GIRLS Striped Camisole Dress', '489000', '15', '63');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('GIRLS Jumper Skirt', '686000', '15', '64');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('GIRLS Corduroy Jumper Skirt', '686000', '15', '64');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('GIRLS AIRism Bra', '391000', '16', '65');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('BOYS Boxer Briefs 3 Pack', '244000', '16', '66');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('GIRLS Shorts 3 Pack', '244000', '16', '66');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('GIRLS Ultra Stretch Long Sleeve Set', '489000', '17', '67');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('KIDS AIRism Stretch Long Sleeve Set', '489000', '17', '67');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Joy Of Print Quilted One Piece Outfit', '391000', '18', '68');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Bodysuit Long Sleeve', '146000', '18', '68');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ribbed Long Sleeve One Piece Outfit', '293000', '18', '68');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Pile Lined Fleece Vest Reversible', '391000', '19', '69');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Fluffy Yarn Fleece Jacket Long Sleeve', '489000', '19', '69');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('AIRism UV Protection Long Sleeve Hoodie', '391000', '19', '69');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Ribbed Crew Neck Long Sleeve T-Shirt', '244000', '19', '70');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Cotton Crew Neck Long Sleeve T-Shirt', '244000', '19', '70');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Relaxed Fit Leggings', '146000', '19', '71');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Corduroy Leggings', '146000', '19', '71');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Relaxed Fit Cropped Leggings', '146000', '19', '71');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('HEATTECH Scoop Neck Long Sleeve T-Shirt', '195000', '20', '72');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Disney KIDEA Long Sleeve', '489000', '20', '73');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Fleece Leggings', '195000', '20', '74');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Leggings', '146000', '20', '74');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('Picturebook Pajamas Long Sleeve', '489000', '20', '75');
INSERT INTO `unifas_service`.`product` (`NAME`, `PRICE`, `CATEGORY_ID`, `SUB_CATEGORY_ID`) VALUES ('My Favorite Toys Long Sleeve Pajamas', '489000', '20', '75');