-- Insert Category
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NGOÀI', 'NỮ', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ÁO', 'NỮ', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('QUẦN', 'NỮ', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐẦM & CHÂN VÁY', 'NỮ', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', 'NỮ', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐỒ MẶC TRONG & ĐỒ LÓT', 'NỮ', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NHÀ', 'NỮ', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('PHỤ KIỆN', 'NỮ', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐỒ BẦU', 'NỮ', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NGOÀI', 'NAM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ÁO', 'NAM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('QUẦN', 'NAM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', 'NAM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐỒ MẶC TRONG & ĐỒ LÓT', 'NAM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NHÀ', 'NAM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('PHỤ KIỆN', 'NAM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NGOÀI', 'TRẺ EM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ÁO', 'TRẺ EM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('QUẦN', 'TRẺ EM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐẦM & CHÂN VÁY', 'TRẺ EM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', 'TRẺ EM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐỒ MẶC TRONG & ĐỒ LÓT', 'TRẺ EM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NHÀ', 'TRẺ EM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('PHỤ KIỆN', 'TRẺ EM', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('TRẺ SƠ SINH (0 - 3 THÁNG)', 'TRẺ SƠ SINH', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('TRẺ SƠ SINH (3 - 24 THÁNG)', 'TRẺ SƠ SINH', '1');
INSERT INTO `unifas_service`.`category` (`NAME`, `GENDER`, `IS_SHOWN`) VALUES ('TRẺ NHỎ (6 THÁNG - 5 NĂM)', 'TRẺ SƠ SINH', '1');
-- Insert Subcategory
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO KHOÁC SIÊU NHẸ & PUFFTECH', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO BLOUSON & ÁO PARKA', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO KHOÁC & ÁO BLAZER', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO CHOÀNG DÁNG DÀI', '1', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO GIẢ LÔNG CỪU', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO NỈ & ÁO HOODIE', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO LEN', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO CARDIGAN', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO THUN', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO THUN IN HỌA TIẾT', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO SƠ MI & ÁO KIỂU', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PEACE FOR ALL', '2', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN JEANS', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN CASUAL', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN ỐNG RỘNG', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN DÀI ĐẾN MẮT CÁ & QUẦN LỬNG', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN TÂY', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN NỈ', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN LEGGING', '3', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐẦM & JUMPSUIT', '4', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('CHÂN VÁY', '4', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', '5', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('HEATTECH ĐỒ MẶC TRONG & QUẦN LÓT GIỮ NHIỆT', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRISM ĐỒ MẶC TRONG', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO BRA', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BRA TOPS', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐỒ LÓT', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN LEGGINGS & QUẦN TẤT', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TẤT', '6', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NHÀ & PYJAMA', '7', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN EASY & RELAXED', '7', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('DÉP ĐI TRONG NHÀ', '7', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TÚI', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('MŨ & MŨ LƯỠI TRAI', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('KHĂN CHOÀNG & KHĂN QUÀNG CỔ', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('GĂNG TAY', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('THẮT LƯNG', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('GIÀY & BỐT', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('Ô', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('KÍNH MÁT', '8', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐỒ BẦU', '9', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO KHOÁC SIÊU NHẸ & PUFFTECH', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO BLOUSON & ÁO PARKA', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRSENSE ÁO KHOÁC SIÊU NHẸ', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO KHOÁC & ÁO BLAZER', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO CHOÀNG DÁNG DÀI', '10', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO GIẢ LÔNG CỪU', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO NỈ & HOODIE', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO LEN', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO THUN', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO POLO', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO THUN IN HỌA TIẾT', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO SƠ MI CASUAL', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO SƠ MI CÔNG SỞ', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PEACE FOR ALL', '11', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN JEAN & QUẦN JEAN MÀU', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN CASUAL', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN DÀI ĐẾN MẮT CÁ', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRSENSE QUẦN DÀI SIÊU NHẸ', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN TÂY', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN DÀI DÁNG RỘNG', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN NỈ', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN SHORT', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN CHINO', '12', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', '13', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('HEATTECH ĐỒ MẶC TRONG & QUẦN LÓT GIỮ NHIỆT', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRISM ĐỒ MẶC TRONG', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN LÓT BOXER & BRIEF', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN LEGGINGS & QUẦN TẤT', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TẤT', '14', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NHÀ & PYJAMA', '15', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN EASY & RELAXED', '15', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('DÉP ĐI TRONG NHÀ', '15', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TÚI', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('MŨ & MŨ LƯỠI TRAI', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('KHĂN CHOÀNG & KHĂN QUÀNG CỔ', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('GĂNG TAY', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('THẮT LƯNG', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('KÍNH MÁT', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('Ô', '16', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO BLOUSON & ÁO PARKA', '17', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO KHOÁC', '17', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO GIẢ LÔNG CỪU', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO NỈ & HOODIE', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO LEN & ÁO CARDIAN', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO THUN', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO THUN IN HỌA TIẾT', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO SƠ MI & ÁO KIỂU', '18', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('JEANS', '19', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN DÀI', '19', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN SHORT', '19', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐẦM', '20', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('CHÂN VÁY', '20', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('SPORT UTILITY WEAR', '21', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('HEATTECH ĐỒ MẶC TRONG & QUẦN LÓT GIỮ NHIỆT', '22', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('AIRISM ĐỒ MẶC TRONG', '22', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO BRA & BRA TOPS', '22', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐỒ LÓT', '22', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TẤT', '22', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NHÀ & PYJAMA', '23', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('GĂNG TAY', '24', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('MŨ', '24', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐỒ DỰ SINH', '25', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PHỤ KIỆN', '25', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NGOÀI', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐỒ LIỀN MẢNH', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('BODYSUIT', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN DÀI & QUẦN LEGGING', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TẤT', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PHỤ KIỆN', '26', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NGOÀI', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ÁO THUN IN HỌA TIẾT', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('QUẦN DÀI & QUẦN LEGGING', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('ĐỒ MẶC NHÀ & PYJAMA', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('HEATTECH ĐỒ MẶC TRONG & QUẦN LÓT GIỮ NHIỆT', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('TẤT', '27', '1');
INSERT INTO `unifas_service`.`sub_category` (`NAME`, `CATEGORY_ID`, `IS_SHOWN`) VALUES ('PHỤ KIỆN', '27', '1');